### ISSUE TITLE
I want to check WSI directly!!!

### ISSUE THREAD

**Issue by linruicheng1997** [uzunb/deep-zoom-image-viewer#1]
Hello author, can this deep-zoom-image-viewer be used to view WSI directly without converting WSI to DZI format?

**Comment by uzunb** [comment]
Hi @linruicheng1997, I have been use OpenSeadragon viewer package for this. You can examine OpenSeadragon documentation in [here](https://openseadragon.github.io/). If I need to short reply for you, deep-zoom-image-viewer supports to following formats:

[Legacy Image Pyramids](https://openseadragon.github.io/examples/tilesource-legacy/)
[IIIF (International Image Interoperability Framework)](https://openseadragon.github.io/examples/tilesource-iiif/)
[DZI (Deep Zoom Images)](https://openseadragon.github.io/examples/tilesource-dzi/)
[OSM (Open Street Maps)](https://openseadragon.github.io/examples/tilesource-osm/)
[TMS (Tiled Map Service)](https://openseadragon.github.io/examples/tilesource-tms/)
[Zoomify](https://openseadragon.github.io/examples/tilesource-zoomify/)
[Custom Tile Sources](https://openseadragon.github.io/examples/tilesource-custom/)
[Simple Image](https://openseadragon.github.io/examples/tilesource-image/)

You can easily open without any converting process.
